Sprint 09
khitrind/ImageFeed pull request #3
Opened 2022-10-11 13:19 UTC by khitrind

2022-10-11 15:43 UTC, ABashkirova requested changes
1. Перепроверить экран профиля пользователя:
   - кнопка logout должна быть размером 24-24
  -  заголовок с именем верного размера 
  - видала, что добавили шрифты в проект, будет здорово если будете их использовать (не обязательное условие)
<img width="250" alt="Screenshot 2022-10-11 at 19 32 50" src="https://user-images.githubusercontent.com/20269264/195136108-49b2db70-c7e3-41ba-8742-67c7ad0b9a10.png"><img width="250" alt="Screenshot 2022-10-11 at 19 33 11" src="https://user-images.githubusercontent.com/20269264/195136156-b2a9aced-1efb-45fd-a661-6c0423025dd8.png">

2. Нужен `@IBAction` для логаута, переменные и функции приватные 
3. На экране `SingleImageViewController` кнопка «Поделиться»:
    - у кнопки не верный отступ от safe area
    - функциональность ширинга сломана 
    <img width="472" alt="Screenshot 2022-10-11 at 19 42 42" src="https://user-images.githubusercontent.com/20269264/195137888-f9794704-dc54-4522-8a3d-8386dc9407dc.png">

2022-10-11 15:43 UTC, ABashkirova commented on ImageFeed/ImageList/ImagesListViewController.swift
> +	private let singleViewIdentifire = "ShowSingleImageView"
```suggestion
	private let singleViewIdentifier = "ShowSingleImageView"
```

2022-10-11 15:43 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +	@IBOutlet weak var profileNameLabel: UILabel!
private

2022-10-11 15:43 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +	@IBAction func didClickShareButtom() {
```suggestion
	@IBAction func didClickShareButton() {
```

2022-10-11 15:43 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +			activityItems: [singleImage],
Попробуйте отправить изображение. 
Скорее всего ничего не выйдет, это поле может принимать текст, URL, изображение, файл, видео. Переданный параметр имеет тип UIView и не сработает

2022-10-11 15:43 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +}
Здесь, к счастью, проблема не на вашей стороне. В уроке подразумевается, что на вход придет изображение достаточно большого размера (вы скоро реализуете загрузку их из сети), и с этими размерами текущий алгоритм будет работать хорошо(параметры скейла подобраны под них). К сожалению, в уроке не учли, что будет использовано изображение из ресурсов очень маленького размера (первое, например, 200 × 132 pixels). **Спасибо, что помогли найти проблему!** 

Авторы уже спешат дополнить урок, а пока предлагают вам самостоятельно обновить ресурсы на те же изображения, только в пределах размеров экрана iPhone X. Тогда решение будет выглядеть сносно, пока не замените на изображения из сети. Также, как временное решение, вы можете попробовать менять размеры scrollView.maximumZoomScale. 

**Про литературу**

Здесь не нужна специальная литература. Алгоритм для задачи вы можете изобрести и сами! 
_Вам дано_
- размеры изображения, 
- размеры экрана

_задача звучит так_ 

> нужно перепозиционировать и перескейлить картинку так, чтобы ее центр совпадал с центром экрана и она занимала все пространство экрана 

Я не могу дать литературы, потому что это одна из геометрических задач, которые иногда приходится решать iOS разработчику, обычно я беру ручку и бумагу и вывожу уравнения :) 
И к нашему счастью, преобразования линейные, тут нет поворотов и деформаций :)

2022-10-12 10:21 UTC, khitrind commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +}
Воу, выглядит супер, попробую на досуге)

Я попробовал другую штуку, положил поверх ScrollView просто View и спозиционировал картинку по ней. Вроде то, что надо:
- картинка скролится;
- картинка нормально вписывается в размер;

2022-10-12 10:26 UTC, khitrind commented
- Размеры шрифтов поправил, но есть одно но( С прошлого спринта у нас есть Bold и Medium а тут много где Regular,
- C кнопкой шаринга, тоже забавно, в макетах отступ не от SafeView а от полосочки в нижней части экрана, а между ней и safeView есть еще какой-то гэп (прикинул на глаз). И еще раз спасибо за идею с геометрической задачкой!)

2022-10-12 10:29 UTC, khitrind commented
Если что, по идее можно просто выставить картинке Aspect to Fill - тогда она будет выглядеть прям как на макете, но кмк на этом этапе - это не основная задач, а не растянутыми они выглядит чуть симпатичнее)

2022-10-12 11:53 UTC, ABashkirova commented
[YS Text and Display .zip](https://github.com/khitrind/ImageFeed/files/9764580/YS.Text.and.Display.zip)
Шрифты, кажется, давали в первом модуле, может поменялось что-то. Не страшно, если нет начертания(можно и системный), главное верный размер.

2022-10-12 11:55 UTC, ABashkirova commented
> C кнопкой шаринга, тоже забавно, в макетах отступ не от SafeView а от полосочки в нижней части экрана, а между ней и safeView есть еще какой-то гэп (прикинул на глаз) 

Не забывайте зажимать cmd, чтобы проверять отступы от разных объектов (не самый очевидный интерфейс, надо привыкнуть).  Сразу видно отступ от safe area 

<img width="351" alt="Screenshot 2022-10-12 at 15 54 16" src="https://user-images.githubusercontent.com/20269264/195336139-5afd2e64-9e80-4456-925f-f074a38f5747.png">

2022-10-12 12:02 UTC, khitrind commented
> > C кнопкой шаринга, тоже забавно, в макетах отступ не от SafeView а от полосочки в нижней части экрана, а между ней и safeView есть еще какой-то гэп (прикинул на глаз)
> 
> Не забывайте зажимать cmd, чтобы проверять отступы от разных объектов (не самый очевидный интерфейс, надо привыкнуть). Сразу видно отступ от safe area
> 
> <img alt="Screenshot 2022-10-12 at 15 54 16" width="351" src="https://user-images.githubusercontent.com/20269264/195336139-5afd2e64-9e80-4456-925f-f074a38f5747.png">

Воу, круто, спасибо!)
Я попробовал добавить большую картинку, она теперь прям на весь экран

2022-10-12 12:03 UTC, khitrind commented
Но выглядит все равно странно, не очень понятно как это в идеале должно выглядеть)

2022-10-12 12:28 UTC, ABashkirova commented
> Если что, по идее можно просто выставить картинке Aspect to Fill - тогда она будет выглядеть прям как на макете, но кмк на этом этапе - это не основная задач, а не растянутыми они выглядит чуть симпатичнее)

тут вы правы, Aspect to Fill не нужен. Сейчас разберемся в чем у вас проблема

2022-10-12 12:30 UTC, khitrind commented
> Я попробовал другую штуку, положил поверх ScrollView просто View и спозиционировал картинку по ней. Вроде то, что надо:
> 
> картинка скролится;
> картинка нормально вписывается в размер;

Центрируется, но скролл не очень работает (вернул как было и добавил пару больших картинок)

2022-10-12 13:38 UTC, ABashkirova requested changes
Дмитрий, еще раз спасибо за интерес и фидбек :) Решение уже в пути, но возможно для вашего потока опоздает, поэтому адаптировано под ваш случай оставила комментарии. 

Работу не приму, потому что есть все еще проблемы с версткой элементов. Давайте еще раз аккуратно проверим размеры, цвета, шрифты и отступы всех элементов. 

Также, будет здорово если вы проверите код-стайл вашего проекта (модификаторы доступа, отступы :) ❤️ 

И не спеша попробуйте осилить описание того, что нужно сделать со скролом. Если возникнут вопросы, можно обсуждать с Наставником) надеюсь поможет достичь правильного* результата. 

*Правильный относительно этого спринта:
<img width="300" alt="Screenshot 2022-10-12 at 17 35 58" src="https://user-images.githubusercontent.com/20269264/195357202-e24c92af-680b-41ca-a4db-a16a594fea19.png"><img width="300" alt="Screenshot 2022-10-12 at 17 35 47" src="https://user-images.githubusercontent.com/20269264/195357220-053c52e8-b876-4ca2-ac2a-4d4b64ae39b4.png">

2022-10-12 13:38 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +			singleImage.image = image
заметьте, что вы верно сделали, выделив две операции на singleImage в одну функцию `setImage`, и здесь выставить новое изображение недостаточно, ведь нужно еще и перескейлить. Давайте исправим  
```suggestion
			setImage()
```

2022-10-12 13:38 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +	@IBOutlet weak var scrollView: UIScrollView!
Не забывайте следить за доступностью переменных и функций :)

2022-10-12 13:38 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +		configureScrollViewScale()
Если раскрыть ~~скобки~~ функции, получим такую последовательность вызовов:

```swift
singleImage.image = image
rescaleScrollViewForPerfectView(image: image)
scrollView.minimumZoomScale = 0.1
scrollView.maximumZoomScale = 1.25
```
Тут важно заметить, что единоразовые  настройки сколвью(таблицы/коллекции), должны делаться до манипуляций с размерами (трансформом) 

порядок вызовов может быть важен, и здесь нужно его поменять местами (из-за комментария ниже)

2022-10-12 13:38 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +		let scale = max(hScale, vScale)
Дмитрий, давайте здесь внесем два небольших изменения в алгоритм. Это то, что предлагают сделать авторы.

Давайте здесь еще учтем, ограничения, которые задали в `minimumZoomScale`, `maximumZoomScale`. Так как вычисление  `var scale = max(hScale, vScale)`, может выдать большие/меньшее значение, чем выставленный диапазон`(0.1, 1.25)`
Сначала мы сравним полученное значение с левым отрезком `0.1`, затем с правым, и выберем в пользу значения в диапазоне. 
Для левого значения, мы можем сказать что нам подойдет наибольшее из двух: `max(0.1, scale)` (попробуйте мысленно подставить `scale` 0.01 и 0.2)
А для правого  — наименьшее из двух `min(scale, 1.25)` (делаем аналогичную мысленную проверку)
Такой clamp записывается мин-максным выражением:

```suggestion
		var scale = max(hScale, vScale)
		let minZoomScale = scrollView.minimumZoomScale
                let maxZoomScale = scrollView.maximumZoomScale
                scale = min(max(minZoomScale, scale), maxZoomScale)
```

Затем, давайте сразу применим найденный зум на скрол вью, вне блока анимации. 
```swift
scrollView.setZoomScale(scale, animated: false)
```
Выставив это значение, скрол вью не должна взять и перерисовать свое содержимое. Изменение настроек применится в следующий такт перерисовки лейаута. Подробнее про это будут рассказывать в следующих главах. 
Чтобы настройка применилась, и фреймы переучивались, можно насильно(😄) заставить сколвью это сделать, следующей строчкой 

```swift
scrollView.layoutIfNeeded()
```
В этот момент, сколвью применит на себе все трансформации которые были к ней применены и отобразит верные размеры контента. Поэтому мы можем забрать размер вот так
```swift
let expectedContentSize = self.scrollView.contentSize
```

Осталось только установить центр. (здесь без изменений, кроме того что зум мы вынесли чуть выше

```swift
UIView.animate(withDuration: 0.25, delay: 0, options: .curveEaseInOut) {
            let x = (expectedContentSize.width - containerSize.width) / 2
            let y = (expectedContentSize.height - containerSize.height) / 2
            self.scrollView.setContentOffset(CGPoint(x: x, y: y), animated: false)
} completion: { _ in }
```

Итоговая функция выглядит вот так:
```swift
private func rescaleScrollViewForPerfectView(image: UIImage) {
        let containerSize = view.bounds.size
        let imageSize = image.size
        let hScale = containerSize.width / imageSize.width
        let vScale = containerSize.height / imageSize.height
        var scale = max(hScale, vScale)
        
        let minZoomScale = scrollView.minimumZoomScale
        let maxZoomScale = scrollView.maximumZoomScale
        scale = min(maxZoomScale, max(minZoomScale, scale))
        
        scrollView.setZoomScale(scale, animated: false)
        scrollView.layoutIfNeeded()
        let expectedContentSize = self.scrollView.contentSize

        UIView.animate(withDuration: 0.25, delay: 0, options: .curveEaseInOut) {
            let x = (expectedContentSize.width - containerSize.width) / 2
            let y = (expectedContentSize.height - containerSize.height) / 2
            self.scrollView.setContentOffset(CGPoint(x: x, y: y), animated: false)
        } completion: { _ in }
}
```

2022-10-12 13:38 UTC, ABashkirova commented on ImageFeed/Presentation/Base.lproj/Main.storyboard
> +                                </subviews>
Давайте все-таки без лайфхака с UIView (откатываемся :) 

Проверьте, куда выставлены констрейнты боковые. Предлагаю убрать UIView, и заново аккуратно выставить констрейнты картинке. Констрейнты должны быть связаны со scrollViewА а не frame layout guide 

Сравните список констрейнтов и то как выглядит экран с картинкой:
<img width="200" alt="Screenshot 2022-10-12 at 16 57 22" src="https://user-images.githubusercontent.com/20269264/195348801-9825b34b-a73f-4f96-a7c1-ef99ac495850.png"><img width="200" alt="Screenshot 2022-10-12 at 16 57 28" src="https://user-images.githubusercontent.com/20269264/195348824-4161588b-7713-477c-b8a1-ee88a38b9993.png">

Если делаете через кнопку внизу IB, то связь с вью меняется если щелкнуть на стрелку у числа 
<img width="368" alt="Screenshot 2022-10-12 at 17 01 39" src="https://user-images.githubusercontent.com/20269264/195349728-274c5f76-d776-4b24-be14-3781f9d5e6aa.png">

Для сравнения, как сториборд выглядит сейчас в проекте: 
<img width="800" alt="Screenshot 2022-10-12 at 16 59 51" src="https://user-images.githubusercontent.com/20269264/195349171-5451ce05-6a4b-4289-97d0-32a1bd7689e6.png">

У картинки должен стоять **Aspect Fit** 

Если вы все верно сделаете по всем комментариям выше, то приложение должно выглядеть вот так:
<img width="200" alt="Screenshot 2022-10-12 at 17 14 56" src="https://user-images.githubusercontent.com/20269264/195352726-cfe242e9-b75f-4a3a-b6ea-4f0c49a4864c.png">
<img width="200" alt=" " src="https://user-images.githubusercontent.com/20269264/195352700-19bc741b-1924-493e-bf25-2708046a31c2.png">

кстати, подложки у кнопки нет, сливается с фоном, залейте картинку прям с кругом в ассеты :)

2022-10-13 06:50 UTC, khitrind commented on ImageFeed/Presentation/Base.lproj/Main.storyboard
> +                                </subviews>
Так вроде так и должно быть?
<img width="320" alt="Screen Shot 2022-10-13 at 9 50 13" src="https://user-images.githubusercontent.com/32079217/195522726-fdae5aa6-15c0-454c-9bae-30c012a43e27.png">

<img width="374" alt="Screen Shot 2022-10-13 at 9 49 56" src="https://user-images.githubusercontent.com/32079217/195522668-fe9beaec-ece7-435b-bbfa-9aaf2b03b8b9.png">

2022-10-13 06:51 UTC, khitrind commented on ImageFeed/Presentation/Base.lproj/Main.storyboard
> +                                </subviews>
Кнопка залита с кругом в ассеты 
![Screen Shot 2022-10-13 at 9 51 23](https://user-images.githubusercontent.com/32079217/195522926-e9a16927-5682-4381-8178-5787b081250e.png)

2022-10-13 06:52 UTC, khitrind commented on ImageFeed/Presentation/Base.lproj/Main.storyboard
> +                                </subviews>
На больших картинках все ок
<img width="574" alt="Screen Shot 2022-10-13 at 9 51 45" src="https://user-images.githubusercontent.com/32079217/195523079-58bcb3ef-1145-4e0a-8e19-5729670615cf.png">

2022-10-13 09:00 UTC, khitrind commented
Привет!) 
- макеты перепроверил, должно быть как нужно;
- констрейнты поправил теперь от SuperView;
- про кнопку шеринга - она вроде и должна сливаться с фоном, кружок виден при условии, что он перекрывается картинкой (оно вроде и логично)

Задачка со скроллом, к наставнику я не оч могу обратиться, так как у меня его нет, я иду немного с опережением своего потока...

**Так что сделал примерно так:**
- На старте вписываем картинку по описанному вами алгоритму, выглядит ок (как на маленьких картинках, так и на больших - последние две в списке);
- если пользователь решил позумить:
  - берем размеры картинки;
  - берем размер scrollView;
  - выставляем внутренние отступы у scrollView так что бы картинка вписывалась по центру (без анимаций всяких);
 Эта штука норм работает с большими картинками, с маленькими, есть проблема, что она дает ускролить их в совсем мизерный размер, что бы пофиксить это в голову приходит только на scrollViewWillZome проверять, что она уже и так нормально вписывается, сохранять размер и на scrollViewDidZoom восстанавливать их (но такое решение кажется костыльным, мне почему-то кажется что есть варианты проще).
 
 Как-то так)

2022-10-13 11:44 UTC, ABashkirova commented on ImageFeed/Presentation/Base.lproj/Main.storyboard
> +                                </subviews>
Извиняюсь, и правда так :)

2022-10-13 11:55 UTC, ABashkirova approved these changes

2022-10-13 11:55 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +		let imgViewSize = singleImage.frame.size;
Кажется вы можете любое решение оставить, которое вам нравится :) оба норм, на мой взгляд
Мне нравится на завершение зума восстанавливать исходный зум картинки, например. Все зависит от требования к продукту, но по этой части кажется его у нас нет. Поэтому тут у вас свобода 👍

Единственное что, точка с запятой - это какое-то наследие objc) подправьте тут, ладно?

2022-10-13 11:56 UTC, khitrind commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +		let imgViewSize = singleImage.frame.size;
наследие javaScript, привычка...

2022-10-13 17:02 UTC, merged